"""Alembic migration template — do not modify this file."""
# create executions table
#
# Revision ID: 6aa3b214b920
# Revises: 0598c75023a8
# Created: 2026-03-17 10:23:36.243531

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6aa3b214b920'
down_revision: Union[str, None] = '0598c75023a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
