"""Alembic migration template — do not modify this file."""
# create files table
#
# Revision ID: f63e66e6ae9d
# Revises: 
# Created: 2026-03-17 11:45:58.147225

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f63e66e6ae9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS blob")
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='blob'
    )
    op.create_index(op.f('ix_blob_files_user_id'), 'files', ['user_id'], unique=False, schema='blob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blob_files_user_id'), table_name='files', schema='blob')
    op.drop_table('files', schema='blob')
    op.execute("DROP SCHEMA IF EXISTS blob CASCADE")
    # ### end Alembic commands ###
