"""create events table

Revision ID: ec1bf979a400
Revises: 
Create Date: 2026-03-17 13:36:50.164622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec1bf979a400'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'events', ['created_at'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_events_event_type'), 'events', ['event_type'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_events_user_id'), 'events', ['user_id'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='events', schema='analytics')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='events', schema='analytics')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='events', schema='analytics')
    op.drop_table('events', schema='analytics')
    # ### end Alembic commands ###
